" colorscheme
" ------------------------------------

syntax on
colorscheme desert

"" Global
set notitle
set directory=~/.vim/tmp
set backupdir=~/.vim/tmp
set clipboard+=unnamedplus,unnamed
set autoread
function! s:remove_dust()
  let cursor = getpos(".")
  " 保存時に行末の空白を除去する
  %s/\s\+$//ge
  " 保存時にtabを2スペースに変換する
  %s/\t/  /ge
  call setpos(".", cursor)
  unlet cursor
endfunction

"Encode
set encoding=UTF-8
set fileencoding=UTF-8
set termencoding=UTF-8

""Search
set incsearch
set hlsearch
set ignorecase
set smartcase
set wrapscan

""Input
set cindent
set shiftwidth=2
set tabstop=2
set expandtab
set softtabstop=2
set whichwrap=b,s,h,l,<,>,[,]

""Display
set number
set title
set showcmd
set ruler
set showmatch
set matchtime=3
set laststatus=2
set cursorline
highlight CursorLine cterm=underline ctermfg=NONE ctermbg=NONE

"" Keybind
nmap <ESC><ESC> ;nohlsearch<CR><ESC>


"" Insert Keybind
inoremap <C-b> <Left>
inoremap <C-f> <Right>
inoremap <C-h> <Backspace>
inoremap <C-d> <Del>
