# -*- sh -*-

# brew
export PATH="/opt/brew/bin:/usr/local/bin:$PATH"
export HOMEBREW_PREFIX=`brew --prefix`
source $HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

source ~/.zsh/base.zsh
source ~/.zsh/prompt.zsh
source ~/.zsh/alias.zsh
source ~/.zsh/completion.zsh
source ~/.zsh/history.zsh
source ~/.zsh/keybinding.zsh
source ~/.zsh/peco.zsh
source ~/.zsh/lang.zsh
source ~/.zsh/ruby.zsh

[ -f ~/.zshrc.local ]  && source ~/.zshrc.local
