# -*- sh -*-

[ -f ~/.zshrc.local ]  && source ~/.zshrc.local

# brew
export PATH="/opt/brew/bin:/usr/local/bin:$PATH"
export HOMEBREW_PREFIX=`brew --prefix`

source ~/.zsh/base.zsh
source ~/.zsh/prompt.zsh
source ~/.zsh/alias.zsh
source ~/.zsh/completion.zsh
source ~/.zsh/history.zsh
source ~/.zsh/keybinding.zsh
source ~/.zsh/peco.zsh
source ~/.zsh/lang.zsh
source ~/.zsh/ruby.zsh

if [ -f $HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
    source $HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi
